### ISSUE TITLE
Install - SQL Build version check has invalid references

### ISSUE THREAD

**Issue by AnonDevelopment** [HotcakesCommerce/cms#14]
Install has minimum requirement of SQL Server 2012. This would be build 11. References to builds are incorrect.

File Impacted: https://github.com/HotcakesCommerce/cms/blob/master/DNN%20Platform/Library/Services/Upgrade/Internals/InstallControllerImpl.cs

Reference: https://support.microsoft.com/en-ph/help/321185/how-to-determine-the-version,-edition-and-update-level-of-sql-server-a

**Comment by WillStrohl** [comment]
Nice catch!  I've left a comment in your PR though.  We need a change made before we can accept it.

**Comment by WillStrohl** [comment]
Thanks for your work on this.  Unfortunately for you, we changed how we're distributing the Hotcakes Commerce CMS.  It's now going to be purely a distribution model, so this issue and its related pull request are going to be closed.  I'm sorry that we can't accept the pull request.
