### ISSUE TITLE
Clean install of 3.0 - site settings cannot be updated

### ISSUE THREAD

**Issue by kingjordan** [HotcakesCommerce/cms#6]
Hello,

I did a clean install of the 3.0 version of HCC.  This was both into a local IIS website on my machine and into a web app inside MS Azure.  The installation worked fine and I ran the store's setup wizard.  I then immediately went to adjust the site settings.  I can not save settings.  I can load the module but when I hit update, I get the following error:

> Error: Site Settings is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at DesktopModules.Admin.Portals.SiteSettings.UpdatePortal(Object sender, EventArgs e) --- End of inner exception stack trace ---

Here is the error from the log file:

> 2017-06-14 20:52:14,112 [RD00155D50C666][Thread:19][ERROR] DotNetNuke.Services.Exceptions.Exceptions - FriendlyMessage="Error: Site Settings is currently unavailable." ctrl="ASP.desktopmodules_admin_portals_sitesettings_ascx" exc="System.NullReferenceException: Object reference not set to an instance of an object.
>    at DesktopModules.Admin.Portals.SiteSettings.UpdatePortal(Object sender, EventArgs e)"

**Comment by kingjordan** [comment]
![ice_screenshot_20170614-145349](https://user-images.githubusercontent.com/5931768/27154463-5d442f42-5112-11e7-968d-6d5ff5302325.png)

**Comment by WillStrohl** [comment]
This is also being discussed here:
https://hotcakes.org/Forums/g/posts/t/30/Site-Settings-do-not-work-on-NEW-instal-of-HCC-3-0

**Comment by kingjordan** [comment]
Hello WIll, 
Where would you like me to follow up with this issue, I see you added it here.  I did provide further feedback on the linked forum, would you like me to put that here aw well?

**Comment by WillStrohl** [comment]
No longer relevant due to the change in distribution model for the Hotcakes Commerce CMS.
